---
title: "Experience"
output: 
  html_document:
    toc: TRUE
    toc_float: FALSE
    theme: cosmo
---

<br>

## Education

I received a BS in statistics from the University of Michigan in May 2020.  I also took a multitude of public health courses at the University of Michigan School of Public Health.  

I am currently a student at Columbia University Mailman School of Public Health pursuing a MS in Biostatistics in the Theory and Methods track (2020-2022).

<br>

## Technical Skills

Proficient in R

Programming Experience in C++ and SQL

<br>

## Research

<b>Research Staff Member at the University of Michigan School of Public Health September 2019-Present</b>

I have been working with Dr. Laura Rozek, professor of Epidemiology, and Dr. Sartor, professor of Biostatistics at the University of Michigan on their cancer research.  I analyzed previously collected data for the Greek Oral Dysplasia Study.  This study is a longitudinal study looking at the progression of oral epithelial dysplasias and if they lead to oral squamous cell carcinomas in a cohort of patients in Greece.  

During my internship(Summer 2019) at John Wiley & Sons, Inc., [I analyzed impact factor and submission data](https://onlinelibrary.wiley.com/doi/abs/10.1002/leap.1285).

<br>

## Experience

<b>Content Management Intern: Wiley, Medford, MA – June 2019-August 2019</b>

• Analyzed Impact Factor and submission data using R and wrote corresponding conclusions, methods, and data tables for a research paper titled Factors Affecting Journal Submission Numbers: Impact Factor and Peer Review Reputation

• Co-led a project with another intern focused on determining which quantitative and qualitative variables influence turnaround times regarding the peer-review process for research articles in the Content Management department

• Developed and executed a project investigating the effect of Open Access on the Impact Factor and other metrics of journals at Wiley

<br>

<b>Retail Administration Intern: Cambridge Savings Bank, Harvard Square - May 2018-August 2018</b>

• Analyzed transaction data and new account data utilizing Excel & pivot tables in order to recommend changes to branch operating hours

• Analyzed personal bankers’ data in order to make recommendations regarding personal bankers’ bonus rewards system

• Created mathematical functions to determine the lowest cost and overall best new account type for various customers regarding their old grandfathered personal and business accounts.

• Used agile scrum method to complete a small group intern project

<br>

## Volunteer

<b>Founder and President of Girl Scouts at the University of Michigan December 2016-April 2020</b>

<br>

## Honors

Golden Key International Honour Society (top 15% of class)

NSCS Honor Society (top 20% of class)

Girl Scout Gold Award Recipient-Noise Induced Hearing Loss Prevention

Project 351 Alumna and Founding Member of the Alumni Leadership Council


<br>

## Publications

[Gaston, T.E., Ounsworth, F., Senders, T., Ritchie, S. and Jones, E. (2020), Factors affecting journal submission numbers: Impact factor and peer review reputation. Learned Publishing.](https://onlinelibrary.wiley.com/doi/abs/10.1002/leap.1285)

