---
title: "Instacart Dashboard"
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: scroll
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)
library(plotly)

data("instacart")
set.seed(1000)
instacart_df <- sample_n(instacart, 1000)
```

Column {data-width=550}
-----------------------------------------------------------------------

### Distribution of the Days Since Prior Order by Department

```{r Chart A}
x <- list(
  title = "<br><br><br>Department"
)
y <- list(
  title = "Days Since Prior Order"
)

instacart_df %>%
  mutate(department = fct_reorder(department, days_since_prior_order)) %>% 
  plot_ly(y = ~days_since_prior_order, color = ~department, type = "box", colors = "viridis") %>%
  layout(xaxis = x, yaxis = y)
```

Column {data-width=550}
-----------------------------------------------------------------------

### Number of Items Ordered in Each Department

```{r Chart B}
x <- list(
  title = "<br><br><br><br>Department"
)
y <- list(
  title = "Count"
)

instacart_df %>% 
  count(department) %>% 
  mutate(department = fct_reorder(department, n)) %>% 
  plot_ly(x = ~department, y = ~n, color = ~department, type = "bar", colors = "viridis") %>%
  layout(xaxis = x, yaxis = y)
```

### Number of Items Added to Cart versus the Order Hour of the Day

```{r Chart C}
x <- list(
  title = "<br><br><br># of Items Added to Cart"
)
y <- list(
  title = "Order Hour of Day"
)

instacart_df %>%
  mutate(text_label = str_c("Department: ", department)) %>% 
  plot_ly(
    x = ~add_to_cart_order, y = ~order_hour_of_day, type = "scatter", mode = "markers",
    color = ~department, text = ~text_label, alpha = 0.5, colors = "viridis") %>%
  layout(xaxis = x, yaxis = y)
```
